apiVersion: v2
name: kuberca
description: Kubernetes Root Cause Analysis System
type: application
version: 0.1.2
appVersion: "0.1.2"
keywords:
  - kubernetes
  - observability
  - root-cause-analysis
  - aiops
home: https://kuberca.io
sources:
  - https://github.com/kuberca-io/kuberca
maintainers:
  - name: IaM DEV
