apiVersion: v2
name: kuberca
description: Kubernetes Root Cause Analysis System
type: application
version: 0.1.2
appVersion: "0.1.2"
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: GitHub
      url: https://github.com/KubeRCA-io/KubeRCA
    - name: Documentation
      url: https://github.com/KubeRCA-io/KubeRCA#readme
keywords:
  - kubernetes
  - observability
  - root-cause-analysis
  - aiops
home: https://kuberca.io
sources:
  - https://github.com/kuberca-io/kuberca
maintainers:
  - name: IaM DEV
